from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from fastapi.exceptions import RequestValidationError
from starlette.exceptions import HTTPException as StarletteHTTPException
import os
import time
import logging
from datetime import datetime
from contextlib import asynccontextmanager

# Import of configuration
from app.config import settings, APP_ENV, APP_DEBUG, APP_NAME, APP_VERSION
from app.middleware import LoggingMiddleware
from app.exceptions import AppException, APIError, app_exception_handler, api_error_handler


# Configuration of logging
logging.basicConfig(
    level=getattr(logging, settings.log_level),
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# ============================================
# Management of the application lifecycle
# ============================================
@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Management of the application lifecycle events
    """
    # Startup
    logger.info(f"Startup of {APP_NAME} v{APP_VERSION}")
    logger.info(f"Environment: {APP_ENV}")
    logger.info(f"Debug mode: {APP_DEBUG}")
    
    # Vérifier la configuration des clés API
    if settings.weather_ai_api_key:
        logger.info("WeatherAI API Key configurée")
    else:
        logger.warning("WeatherAI API Key non configurée")
    
    if settings.openweather_api_key:
        logger.info("OpenWeatherMap API Key configurée (fallback)")
    else:
        logger.info("OpenWeatherMap API Key non configurée")
    
    yield
    
    # Arrêt
    logger.info(f"👋 Stop the {APP_NAME}")

# ============================================
# Creation of the application
# ============================================
app = FastAPI(
    title=APP_NAME,
    description="""
    ## 🌤️ WeatherAI Integration
    
    App integrating the WeatherAI API for weather data.
    
    ### Main Features:
    - Real-time weather and forecasts
    - AI summaries generated by Gemini
    - Account usage tracking
    - Multi-API support (WeatherAI + OpenWeatherMap fallback)
    
    ### Endpoints available:
    - `GET /` - Home page
    - `GET /health` - Application status
    - `GET /api/weather` - Weather data
    - `GET /api/usage` - Account usage
    - `GET /config` - Configuration (dev only)
    """,
    version=APP_VERSION,
    docs_url="/docs" if APP_DEBUG else None,
    redoc_url="/redoc" if APP_DEBUG else None,
    lifespan=lifespan
)

app.add_middleware(LoggingMiddleware)
app.add_exception_handler(AppException, app_exception_handler)
app.add_exception_handler(APIError, api_error_handler)

# ============================================
# Middleware personnalized
# ============================================

# Middleware to measure response time
@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    """
    Adds an X-Process-Time header to each response
    """
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    response.headers["X-Process-Time"] = str(process_time)
    
    # Log of requests
    logger.info(
        f"{request.method} {request.url.path} - "
        f"Status: {response.status_code} - "
        f"Time: {process_time:.3f}s"
    )
    
    return response

# Middleware to handle global errors
@app.middleware("http")
async def error_handling_middleware(request: Request, call_next):
    """
    Capture global errors and return a formatted response
    """
    try:
        response = await call_next(request)
        return response
    except Exception as e:
        logger.error(f"Unhandled error: {str(e)}", exc_info=True)
        return JSONResponse(
            status_code=500,
            content={
                "error": "Internal Server Error",
                "detail": str(e) if APP_DEBUG else "An error occurred",
                "path": request.url.path,
                "timestamp": datetime.now().isoformat()
            }
        )

# ============================================
# Configuration CORS
# ============================================
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins if isinstance(settings.cors_origins, list) else ["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ============================================
# Custom exception handlers
# ============================================

@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request: Request, exc: StarletteHTTPException):
    """
    Handles HTTP exceptions with a consistent format
    """
    return JSONResponse(
        status_code=exc.status_code,
        content={
            "error": exc.detail,
            "status_code": exc.status_code,
            "path": request.url.path,
            "timestamp": datetime.now().isoformat()
        }
    )

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    """
    Handles validation errors with details
    """
    errors = []
    for error in exc.errors():
        errors.append({
            "field": ".".join(str(loc) for loc in error["loc"]),
            "message": error["msg"],
            "type": error["type"]
        })
    
    return JSONResponse(
        status_code=422,
        content={
            "error": "Validation Error",
            "details": errors,
            "path": request.url.path,
            "timestamp": datetime.now().isoformat()
        }
    )

# ============================================
# Routes
# ============================================

# Route racine
@app.get("/")
async def root():
    """
    Main endpoint of the API
    """
    return {
        "message": f"Welcome to {APP_NAME}",
        "version": APP_VERSION,
        "environment": APP_ENV,
        "endpoints": {
            "docs": "/docs" if APP_DEBUG else "Not available",
            "health": "/health",
            "weather": "/api/weather?lat=-1.2921&lon=36.8219",
            "usage": "/api/usage",
            "config": "/config" if APP_DEBUG else "Not available"
        },
        "configuration": {
            "weather_ai_configured": bool(settings.weather_ai_api_key),
            "openweather_configured": bool(settings.openweather_api_key),
            "environment": APP_ENV
        },
        "timestamp": datetime.now().isoformat()
    }

# Route de santé améliorée
@app.get("/health")
async def health_check():
    """
    Check the health of the application with details
    """
    # Check the connectivity of the APIs (simulated for now)
    api_status = {
        "weather_ai": {
            "configured": bool(settings.weather_ai_api_key),
            "status": "unknown"  # Will be verified by the service
        },
        "openweather": {
            "configured": bool(settings.openweather_api_key),
            "status": "unknown"
        }
    }
    
    # Check the dependencies    
    dependencies = {
        "python_version": "3.12",
        "fastapi": "0.104.1",
        "pydantic": "2.5.0"
    }
    
    return {
        "status": "healthy",
        "service": APP_NAME,
        "version": APP_VERSION,
        "environment": APP_ENV,
        "uptime": time.time() - start_time if 'start_time' in globals() else 0,
        "api_status": api_status,
        "dependencies": dependencies,
        "timestamp": datetime.now().isoformat()
    }

# Route de configuration (développement uniquement)
@app.get("/config")
async def get_config():
    """
    Display the application configuration
    RReserved for development (disabled in production)
    """
    if APP_ENV == "production":
        raise HTTPException(
            status_code=403,
            detail="Configuration non disponible en production"
        )
    
    # Masquer les clés API complètes
    def mask_key(key: str) -> str:
        if not key:
            return "Non configurée"
        if len(key) <= 8:
            return "***"
        return f"{key[:4]}...{key[-4:]}"
    
    return {
        "app": {
            "name": APP_NAME,
            "version": APP_VERSION,
            "environment": APP_ENV,
            "debug": APP_DEBUG,
            "log_level": LOG_LEVEL
        },
        "server": {
            "host": settings.host,
            "port": settings.port
        },
        "cors": {
            "origins": settings.cors_origins
        },
        "apis": {
            "weather_ai": {
                "url": settings.weather_ai_url,
                "key": mask_key(settings.weather_ai_api_key),
                "configured": bool(settings.weather_ai_api_key)
            },
            "openweather": {
                "key": mask_key(settings.openweather_api_key),
                "configured": bool(settings.openweather_api_key)
            }
        },
        "timestamp": datetime.now().isoformat()
    }

# Route of métrics (for monitoring)
@app.get("/metrics")
async def get_metrics():
    """
    Métriques simples de l'application
    """
    # Note: for the métrics advanced, using Prometheus
    return {
        "service": APP_NAME,
        "version": APP_VERSION,
        "environment": APP_ENV,
        "timestamp": datetime.now().isoformat(),
        "configuration_status": {
            "weather_ai": "configured" if settings.weather_ai_api_key else "not_configured",
            "openweather": "configured" if settings.openweather_api_key else "not_configured"
        }
    }

# Route for testing errors (development)
@app.get("/test-error/{error_type}")
async def test_error(error_type: str):
    """
    Endpoint for testing error handling (development only)
    """
    if APP_ENV == "production":
        raise HTTPException(status_code=403, detail="Non available in production")
    
    if error_type == "400":
        raise HTTPException(status_code=400, detail="Client error simulated")
    elif error_type == "404":
        raise HTTPException(status_code=404, detail="Resource not found simulated")
    elif error_type == "500":
        raise Exception("Server error simulated")
    elif error_type == "validation":
        # Causes a validation error
        from pydantic import BaseModel
        class TestModel(BaseModel):
            required_field: str
        TestModel()  #  required_field
    else:
        return {"message": f"Test successful: {error_type}"}

# ============================================
# Endpoints for the APIs (WeatherAI and OpenWeatherMap) will be implemented in separate modules
# ============================================
if __name__ == "__main__":
    import uvicorn
    
    # Variable for the uptime
    start_time = time.time()
    
    uvicorn.run(
        "app.main:app",
        host=settings.host,
        port=settings.port,
        reload=APP_DEBUG,
        log_level=settings.log_level.lower()
    )
else:
    # Variable for the uptime when imported
    start_time = time.time()